"""
Django management command: refresh_cookies

Semi-automated YouTube cookie refresh for yt-dlp.

WHY SEMI-AUTOMATED?
  YouTube actively rotates cookies on any open YouTube tab as a security
  measure. The official yt-dlp guidance (2026) is:
    1. Open a private/incognito browser window
    2. Log into YouTube
    3. Navigate to https://www.youtube.com/robots.txt
    4. Export cookies for youtube.com
    5. Close the window — never re-open the session
  Fully unattended Playwright login fails because Google detects automation
  and triggers CAPTCHA. So this command automates everything EXCEPT the
  login step, which you do by hand in a visible browser window.

USAGE
  pip install playwright
  python -m playwright install chromium
  python manage.py refresh_cookies

  A browser will open. Log in. Navigate to youtube.com/robots.txt.
  Then press Enter in the terminal. cookies.txt will be replaced atomically.
"""

import os
import sys
import time
import tempfile
import shutil
import datetime

from django.core.management.base import BaseCommand
from dotenv import load_dotenv

load_dotenv()

YT_COOKIES_PATH = os.getenv("YT_COOKIES_PATH", "cookies.txt")


def cookies_to_netscape(cookies):
    """
    Convert Playwright cookies (list of dicts) into Netscape cookies.txt format
    that yt-dlp expects.
    """
    lines = [
        "# Netscape HTTP Cookie File",
        f"# Generated by refresh_cookies on {datetime.datetime.utcnow().isoformat()}Z",
        "# This is a generated file! Do not edit.",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        # Only export Google/YouTube cookies — drop noise from other origins.
        if not any(d in domain for d in ("youtube.com", "google.com")):
            continue
        include_subdomain = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0)) if c.get("expires", -1) > 0 else 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([
            domain, include_subdomain, path, secure, str(expires), name, value
        ]))
    return "\n".join(lines) + "\n"


class Command(BaseCommand):
    help = "Refresh YouTube cookies.txt via Playwright (semi-automated)."

    def add_arguments(self, parser):
        parser.add_argument(
            "--headless",
            action="store_true",
            help="Run headless (not recommended — Google will likely block).",
        )
        parser.add_argument(
            "--output",
            type=str,
            default=YT_COOKIES_PATH,
            help=f"Where to write cookies.txt (default: {YT_COOKIES_PATH})",
        )

    def handle(self, *args, **options):
        try:
            from playwright.sync_api import sync_playwright
        except ImportError:
            self.stdout.write(self.style.ERROR(
                "Playwright is not installed.\n"
                "Run:\n"
                "  pip install playwright\n"
                "  python -m playwright install chromium"
            ))
            sys.exit(1)

        output_path = options["output"]
        headless = options["headless"]

        self.stdout.write(self.style.WARNING(
            "\n=== YouTube Cookie Refresh ===\n"
            "A browser will open. Please:\n"
            "  1. Log into your YouTube account\n"
            "  2. Navigate to https://www.youtube.com/robots.txt\n"
            "     (this prevents cookie rotation per yt-dlp official guide)\n"
            "  3. Come back to this terminal and press Enter\n"
        ))

        with sync_playwright() as p:
            browser = p.chromium.launch(headless=headless)
            # Use a fresh context = like an incognito window, which is what
            # the yt-dlp wiki specifically recommends.
            context = browser.new_context()
            page = context.new_page()
            page.goto("https://accounts.google.com/ServiceLogin?service=youtube")

            self.stdout.write("Browser is open. Log in, then go to youtube.com/robots.txt.")
            try:
                input("Press Enter here when ready to capture cookies... ")
            except KeyboardInterrupt:
                self.stdout.write(self.style.ERROR("\nCancelled."))
                browser.close()
                sys.exit(1)

            cookies = context.cookies()
            # CRITICAL: close the context/browser BEFORE writing the file,
            # so the YouTube session is never re-opened. This keeps cookies
            # from being rotated/invalidated.
            context.close()
            browser.close()

        netscape = cookies_to_netscape(cookies)
        yt_cookie_count = netscape.count("youtube.com") + netscape.count(".youtube.com")
        if yt_cookie_count == 0:
            self.stdout.write(self.style.ERROR(
                "No YouTube cookies captured. Did you actually log in?"
            ))
            sys.exit(1)

        # Atomic replace: write to a temp file, then rename.
        # Also keep a timestamped backup of the previous cookies file.
        if os.path.exists(output_path):
            backup = f"{output_path}.bak-{int(time.time())}"
            shutil.copy2(output_path, backup)
            self.stdout.write(f"Backed up previous cookies -> {backup}")

        fd, tmp_path = tempfile.mkstemp(prefix="cookies_", suffix=".txt",
                                        dir=os.path.dirname(os.path.abspath(output_path)) or ".")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(netscape)
            os.replace(tmp_path, output_path)
        except Exception:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise

        self.stdout.write(self.style.SUCCESS(
            f"Wrote {output_path} with {yt_cookie_count} YouTube cookie entries."
        ))
        self.stdout.write(
            "Tip: cookies typically last ~2 weeks. Re-run when downloads fail."
        )